name = "MooX-Role-CloneSet"
# badges = ["travis"]
authority="cpan:ROAM"
license = "artistic_2"

module_maker="ModuleBuildTiny"

[no_index]
directory = [
  "t",
  "xt",
  "inc",
  "share",
  "eg",
  "examples",
  "author",
  "builder",
  "tools",
]
